/**
 * VRM Standardized Master Products Dataset
 * Synchronized directly from "VRM - Product - Standardized Names.xlsx"
 * Total Products: 285
 */
export const VRM_PRODUCTS = [
  {
    "sno": "1",
    "material": "HDG",
    "code": "L500",
    "name": "LEG 500 mm (HDG)",
    "sections": "500mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "2",
    "material": "HDG",
    "code": "L650",
    "name": "LEG 650 mm (HDG)",
    "sections": "650mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "3",
    "material": "HDG",
    "code": "L900",
    "name": "LEG 900 mm (HDG)",
    "sections": "900mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "4",
    "material": "HDG",
    "code": "L1000",
    "name": "LEG 1000 mm (HDG)",
    "sections": "1000mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "5",
    "material": "HDG",
    "code": "L1200",
    "name": "LEG 1200 mm (HDG)",
    "sections": "1200mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "6",
    "material": "HDG",
    "code": "L1300",
    "name": "LEG 1300 mm (HDG)",
    "sections": "1300mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "7",
    "material": "HDG",
    "code": "L1500",
    "name": "LEG 1500 mm (HDG)",
    "sections": "1500mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "8",
    "material": "HDG",
    "code": "L1800",
    "name": "LEG 1800 mm (HDG)",
    "sections": "1800mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "9",
    "material": "HDG",
    "code": "L2000",
    "name": "LEG 2000 mm (HDG)",
    "sections": "2000mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "10",
    "material": "HDG",
    "code": "L2500",
    "name": "LEG 2500 mm (HDG)",
    "sections": "2500mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "11",
    "material": "HDG",
    "code": "L3000",
    "name": "LEG 3000 mm (HDG)",
    "sections": "3000mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "12",
    "material": "HDG",
    "code": "R1600",
    "name": "RAFTER 1600 mm (HDG)",
    "sections": "1600mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "13",
    "material": "HDG",
    "code": "R2950",
    "name": "RAFTER 2950 mm (HDG)",
    "sections": "2950mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "14",
    "material": "HDG",
    "code": "R3350",
    "name": "RAFTER 3350 mm (HDG)",
    "sections": "3350mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "15",
    "material": "HDG",
    "code": "R3900",
    "name": "RAFTER 3900 mm (HDG)",
    "sections": "3900mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "16",
    "material": "GAL",
    "code": "GR1600",
    "name": "RAFTER 1600 mm (GAL)",
    "sections": "1600mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "17",
    "material": "GAL",
    "code": "GR2950",
    "name": "RAFTER 2950 mm (GAL)",
    "sections": "2950mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "18",
    "material": "GAL",
    "code": "GR3350",
    "name": "RAFTER 3350 mm (GAL)",
    "sections": "3350mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "19",
    "material": "GAL",
    "code": "GR3900",
    "name": "RAFTER 3900 mm (GAL)",
    "sections": "3900mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "20",
    "material": "HDG",
    "code": "CB2400",
    "name": "Cross Bracing -2400mm (HDG)",
    "sections": "2400mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "21",
    "material": "HDG",
    "code": "CB3000",
    "name": "Cross Bracing -3000mm (HDG)",
    "sections": "3000mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "22",
    "material": "GAL",
    "code": "HP2400",
    "name": "Purlin 'HAT' Type - 2400 mm (GAL)",
    "sections": "2400mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "23",
    "material": "GAL",
    "code": "HP2485",
    "name": "Purlin 'HAT' Type - 2485 mm (GAL)",
    "sections": "2485mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "24",
    "material": "GAL",
    "code": "HP2500",
    "name": "Purlin 'HAT' Type - 2500 mm (GAL)",
    "sections": "2500mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "25",
    "material": "GAL",
    "code": "HP3000",
    "name": "Purlin 'HAT' Type - 3000 mm (GAL)",
    "sections": "3000mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "26",
    "material": "GAL",
    "code": "HP3035",
    "name": "Purlin 'HAT' Type - 3035 mm (GAL)",
    "sections": "3035mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "27",
    "material": "GAL",
    "code": "HP3330",
    "name": "Purlin 'HAT' Type - 3330 mm (GAL)",
    "sections": "3330mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "28",
    "material": "GAL",
    "code": "HP3600",
    "name": "Purlin 'HAT' Type - 3600 mm (GAL)",
    "sections": "3600mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "29",
    "material": "HDG",
    "code": "CP2400",
    "name": "Purlin 'C' Type - 2400 mm (HDG)",
    "sections": "2400mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "30",
    "material": "HDG",
    "code": "CP3000",
    "name": "Purlin 'C' Type - 3000 mm (HDG)",
    "sections": "3000mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "31",
    "material": "HDG",
    "code": "CP3200",
    "name": "Purlin 'C' Type - 3200 mm (HDG)",
    "sections": "3200mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "32",
    "material": "HDG",
    "code": "CP3600",
    "name": "Purlin 'C' Type - 3600 mm (HDG)",
    "sections": "3600mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "33",
    "material": "6063T6",
    "code": "MR100N",
    "name": "100mm mini rail (new)",
    "sections": "300MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "34",
    "material": "6063T6",
    "code": "MR100O",
    "name": "100mm mini rail (old)",
    "sections": "300MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "35",
    "material": "6063T6",
    "code": "MR40",
    "name": "40mm mini rail",
    "sections": "300MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "36",
    "material": "6063T6",
    "code": "MR60",
    "name": "60mm mini rail",
    "sections": "300MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "37",
    "material": "6063T6",
    "code": "AR100",
    "name": "100mm Adhesive rail",
    "sections": "300MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "38",
    "material": "6063T6",
    "code": "AR120",
    "name": "120mm Adhesive rail",
    "sections": "300MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "39",
    "material": "6063T6",
    "code": "CC4.8N",
    "name": "Double C Rail 4.8m (new)",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "40",
    "material": "6063T6",
    "code": "CC4.8O",
    "name": "Double C Rail 4.8m (old)",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "41",
    "material": "6063T6",
    "code": "CC3.6",
    "name": "Double C Rail 3.6m",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "42",
    "material": "6063T6",
    "code": "CC2.4",
    "name": "Double C Rail 2.4m",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "43",
    "material": "6063T6",
    "code": "CC1.2",
    "name": "Double C Rail 1.2m",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "44",
    "material": "6063T6",
    "code": "SR3.6",
    "name": "Struct Rail 3.6mm",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "45",
    "material": "6063T6",
    "code": "SR2.4",
    "name": "Struct Rail 2.4mm",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "46",
    "material": "6063T6",
    "code": "UM",
    "name": "Universal Mid Clamp",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "47",
    "material": "6063T6",
    "code": "UE",
    "name": "Universal End Clamp",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "48",
    "material": "6063T6",
    "code": "LC",
    "name": "Locking Clamp",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "49",
    "material": "6063T6",
    "code": "LC(N)",
    "name": "Locking Clamp (New)",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "50",
    "material": "6063T6",
    "code": "EC35",
    "name": "End Clamp 35 mm",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "51",
    "material": "6063T6",
    "code": "MC35",
    "name": "Mid Clamp 35mm",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "52",
    "material": "6063T6",
    "code": "MC30",
    "name": "Mid Clamp 30mm",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "53",
    "material": "6063T6",
    "code": "EC30",
    "name": "End Clamp 30 mm",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "54",
    "material": "6063T6",
    "code": "T10",
    "name": "T nut 10mm",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "55",
    "material": "6063T6",
    "code": "T8",
    "name": "T nut 8mm",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "56",
    "material": "6063T6",
    "code": "ALB",
    "name": "L Bracket",
    "sections": "OWN PROFILE",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "57",
    "material": "NR 70160",
    "code": "E40",
    "name": "EPDM 40*40",
    "sections": "40*40*2MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "58",
    "material": "NR 70160",
    "code": "E100",
    "name": "EPDM 100*25",
    "sections": "100*25*2MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "59",
    "material": "NR 70160",
    "code": "E80",
    "name": "EPDM 80*25",
    "sections": "80*25*2MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "60",
    "material": "NR 70160",
    "code": "E150",
    "name": "EPDM 150*25",
    "sections": "150*25*2MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "61",
    "material": "HDG",
    "code": "LB",
    "name": "L BRACING",
    "sections": "1260*50/40*2MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "62",
    "material": "HDG",
    "code": "BP",
    "name": "BRACING PLATE 80*160",
    "sections": "80*160*2MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "63",
    "material": "HDG",
    "code": "PC50",
    "name": "PURLIN CLEAT 50*60*60",
    "sections": "50*60*60*3MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "64",
    "material": "HDG",
    "code": "PC130",
    "name": "PURLIN CLEAT 130*60*70",
    "sections": "130*60*70*3MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "65",
    "material": "HDG",
    "code": "RC40",
    "name": "RAFTER CLEAT 500*40",
    "sections": "500*40*3MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "66",
    "material": "HDG",
    "code": "RC70",
    "name": "RAFTER CLEAT 500*70",
    "sections": "500*70*3MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "67",
    "material": "HDG",
    "code": "B150",
    "name": "BASE PLATE 150*150",
    "sections": "150*150*5MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "68",
    "material": "HDG",
    "code": "B200",
    "name": "BASE PLATE 200*200",
    "sections": "200*200*5MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "69",
    "material": "SS304",
    "code": "AM8*20",
    "name": "SS304 Allen Bolt M8*20",
    "sections": "M8*20",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "70",
    "material": "SS304",
    "code": "SWM8",
    "name": "SS304 Spring Washer - M8",
    "sections": "M8",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "71",
    "material": "SS304",
    "code": "AM8*30",
    "name": "SS304 Allen Bolt M8*30",
    "sections": "M8*30",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "72",
    "material": "SS304",
    "code": "AM8*50",
    "name": "SS304 Allen Bolt M8*50",
    "sections": "M8*50",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "73",
    "material": "SS304",
    "code": "SNM8",
    "name": "SS304 M8 Square Nut",
    "sections": "M8",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "74",
    "material": "SS304",
    "code": "PWM8",
    "name": "SS304 Plain Washer - M8",
    "sections": "M8",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "75",
    "material": "SS304",
    "code": "HNM8",
    "name": "SS304 Hex Nut M8",
    "sections": "M8",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "76",
    "material": "SS304",
    "code": "HM8*30",
    "name": "SS304 Hexa Bolt M8*30",
    "sections": "M8*30",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "77",
    "material": "SS304",
    "code": "AM6*30",
    "name": "Allen bolt SS304-M6*30",
    "sections": "M6*30",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "78",
    "material": "SS304",
    "code": "AM6*50",
    "name": "Allen bolt SS304-M6*50",
    "sections": "M6*50",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "79",
    "material": "SS304",
    "code": "HM6*80",
    "name": "SS 304 Hex Bolt - M6*80",
    "sections": "M6*80",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "80",
    "material": "SS304",
    "code": "HM6*90",
    "name": "SS 304 Hex Bolt - M6*90",
    "sections": "M6*90",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "81",
    "material": "SS304",
    "code": "PWM6",
    "name": "SS304 M6 Plain Washer",
    "sections": "M6",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "82",
    "material": "SS304",
    "code": "SWM6",
    "name": "SS304 M6 Spring Washer",
    "sections": "M6",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "83",
    "material": "SS304",
    "code": "HNM6",
    "name": "SS304 M6 Hexa Nut",
    "sections": "M6",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "84",
    "material": "SS304",
    "code": "SHM10*30",
    "name": "SS304 Hexa Bolt M10*30",
    "sections": "M10*30",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "85",
    "material": "SS304",
    "code": "SHM12*30",
    "name": "SS304 Hexa Bolt M12*30",
    "sections": "M12*30",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "86",
    "material": "SS304",
    "code": "PWBM8",
    "name": "SS304 M8 Plate Washer ID-8.5mm OD-25mm",
    "sections": "M8",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "87",
    "material": "SS304",
    "code": "AM8*25",
    "name": "SS304 Allen Bolt M8*25",
    "sections": "M8*25",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "88",
    "material": "HDG",
    "code": "ANM10*100",
    "name": "GI Anchor Bolt M10*100",
    "sections": "M10*100",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "89",
    "material": "HDG",
    "code": "ANM8*100",
    "name": "GI Anchor Bolt M8*100",
    "sections": "M8*100",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "90",
    "material": "Grade 8.8(HDG)",
    "code": "HHM10*30",
    "name": "HDG M10*30 HEX BOLT +PW+SW+NUT",
    "sections": "M10*30",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "91",
    "material": "Grade 8.8(HDG)",
    "code": "HHM12*30",
    "name": "HDG M12*30 HEX BOLT +PW+SW+NUT",
    "sections": "M12*30",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "92",
    "material": "SS304",
    "code": "MC6",
    "name": "M CLAMP (M6)",
    "sections": "M6",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "93",
    "material": "SS304",
    "code": "CC6",
    "name": "C CLAMP",
    "sections": "",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "94",
    "material": "SS304",
    "code": "STS3",
    "name": "SELF TAPPING SCREW 3 INCH",
    "sections": "3 INCH",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "95",
    "material": "SS304",
    "code": "STS3/4",
    "name": "SELF TAPPING SCREW 3/4 INCH",
    "sections": "3/4 INCH",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "96",
    "material": "SS304",
    "code": "STS1",
    "name": "SELF TAPPING SCREW 1 INCH",
    "sections": "1 INCH",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "97",
    "material": "ACDB",
    "code": "AC(1-5)",
    "name": "ACDB (1-5 KW) With MCB AND SPD",
    "sections": "1-5 KW",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "98",
    "material": "DCDB",
    "code": "DC(1-5)",
    "name": "DCDB (1-5 KW) With MCB, FUSE AND SPD",
    "sections": "1-5 KW",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "99",
    "material": "ACDB",
    "code": "AC(5-10)",
    "name": "ACDB (5-10 KW) With MCB AND SPD",
    "sections": "5-10 KW",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "100",
    "material": "DCDB",
    "code": "DC(5-10)",
    "name": "DCDB (5-10 KW) With MCB, FUSE AND SPD",
    "sections": "5-10 KW",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "101",
    "material": "COPPER BONDED",
    "code": "ER1",
    "name": "EARTH ROD 14mm",
    "sections": "1M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "102",
    "material": "COPPER BONDED",
    "code": "ER2",
    "name": "EARTH ROD 14mm",
    "sections": "2M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "101",
    "material": "COPPER BONDED",
    "code": "ER3",
    "name": "EARTH ROD 14mm",
    "sections": "3M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "102",
    "material": "COPPER BONDED",
    "code": "LA1",
    "name": "LIGHTNING ARRESTER 16mm",
    "sections": "1M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "105",
    "material": "GAL",
    "code": "CER1",
    "name": "CHEMICAL EARTH ROD",
    "sections": "1M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "106",
    "material": "GAL",
    "code": "CER2",
    "name": "CHEMICAL EARTH ROD",
    "sections": "2M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "103",
    "material": "GAL",
    "code": "CER3",
    "name": "CHEMICAL EARTH ROD",
    "sections": "3M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "104",
    "material": "SS304",
    "code": "ELA",
    "name": "ESE LIGHTNING ARRESTER",
    "sections": "",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "105",
    "material": "POLYMER",
    "code": "EPC6",
    "name": "EARTH PIT CHAMBER",
    "sections": "6 INCH",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "106",
    "material": "EARTHING GRADE",
    "code": "CB10",
    "name": "CHEMICAL BAG 10kg",
    "sections": "10 KG",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "107",
    "material": "HDG",
    "code": "ES",
    "name": "EARTH STRIP",
    "sections": "",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "108",
    "material": "FRLS",
    "code": "ACB4",
    "name": "AC CABLE 4Sqmm. (Black)",
    "sections": "4SQMM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "109",
    "material": "FRLS",
    "code": "ACR4",
    "name": "AC CABLE 4Sqmm. (Red)",
    "sections": "4SQMM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "110",
    "material": "FRLS",
    "code": "DCB4",
    "name": "DC CABLE 4Sqmm. (Black)",
    "sections": "4SQMM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "111",
    "material": "FRLS",
    "code": "DCR4",
    "name": "DC CABLE 4Sqmm. (Red)",
    "sections": "4SQMM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "112",
    "material": "FRLS",
    "code": "ECG4",
    "name": "EARTHING CABLE 4Sqmm. (Green)",
    "sections": "4SQMM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "113",
    "material": "FRLS",
    "code": "ACB6",
    "name": "AC CABLE 6Sqmm. (Black)",
    "sections": "6SQMM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "114",
    "material": "FRLS",
    "code": "ACR6",
    "name": "AC CABLE 6Sqmm. (Red)",
    "sections": "6SQMM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "115",
    "material": "FRLS",
    "code": "DCB6",
    "name": "DC CABLE 6Sqmm. (Black)",
    "sections": "6SQMM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "116",
    "material": "FRLS",
    "code": "DCR6",
    "name": "DC CABLE 6Sqmm. (Red)",
    "sections": "6SQMM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "117",
    "material": "FRLS",
    "code": "ECG6",
    "name": "EARTHING CABLE 6Sqmm. (Green)",
    "sections": "6SQMM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "118",
    "material": "FRLS",
    "code": "ECG16",
    "name": "EARTHING CABLE 16Sqmm. (Green)",
    "sections": "16SQMM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "119",
    "material": "6063T6",
    "code": "TT1",
    "name": "TRIANGLE TOP",
    "sections": "1000M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "120",
    "material": "6063T6",
    "code": "TB1",
    "name": "TRIANGLE BOTTOM",
    "sections": "1000M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "121",
    "material": "6063T6",
    "code": "TT1.5",
    "name": "TRIANGLE TOP",
    "sections": "1500M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "122",
    "material": "6063T6",
    "code": "TB1.5",
    "name": "TRIANGLE BOTTOM",
    "sections": "1500M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "123",
    "material": "6063T6",
    "code": "TT2",
    "name": "TRIANGLE TOP",
    "sections": "2000M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "124",
    "material": "6063T6",
    "code": "TB2",
    "name": "TRIANGLE BOTTOM",
    "sections": "2000M",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "125",
    "material": "6063T6",
    "code": "TMS",
    "name": "TRIANGLE MID SECTION",
    "sections": "",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "126",
    "material": "6063T6",
    "code": "MR75",
    "name": "MINI RAIL 75MM NEW",
    "sections": "75MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "127",
    "material": "6063T6",
    "code": "MR100",
    "name": "MINI RAIL 100MM NEW",
    "sections": "100MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "128",
    "material": "6063T6",
    "code": "MR120",
    "name": "MINI RAIL 120MM NEW",
    "sections": "120MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "129",
    "material": "DEYE",
    "code": "DS1.5",
    "name": "DEYE ONGRID 1.5KW Single Phase",
    "sections": "1.5KW",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "130",
    "material": "DEYE",
    "code": "SC2.2",
    "name": "DEYE ONGRID  2.2KW Single Phase",
    "sections": "2.2KW",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "131",
    "material": "DEYE",
    "code": "DS3",
    "name": "DEYE ONGRID  3KW Single Phase",
    "sections": "3KW",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "132",
    "material": "DEYE",
    "code": "DS3.3",
    "name": "DEYE ONGRID  3.3KW Single Phase",
    "sections": "3.3KW",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "133",
    "material": "DEYE",
    "code": "DS3.6",
    "name": "DEYE ONGRID 3.6KW Single Phase",
    "sections": "3.6KW",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "134",
    "material": "DEYE",
    "code": "DS4",
    "name": "DEYE ONGRID 4KW Single Phase",
    "sections": "4KW",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "135",
    "material": "DEYE",
    "code": "DS5",
    "name": "DEYE ONGRID 5KW Single Phase",
    "sections": "5KW",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "136",
    "material": "DEYE",
    "code": "DT5",
    "name": "DEYE ONGRID 5KW Three Phase",
    "sections": "5KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "137",
    "material": "DEYE",
    "code": "DT6",
    "name": "DEYE ONGRID 6KW Three Phase",
    "sections": "6KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "138",
    "material": "DEYE",
    "code": "DT8",
    "name": "DEYE ONGRID 8KW Three Phase",
    "sections": "8KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "139",
    "material": "DEYE",
    "code": "DT10",
    "name": "DEYE ONGRID 10KW Three Phase",
    "sections": "10KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "140",
    "material": "DEYE",
    "code": "DT12",
    "name": "DEYE ONGRID 12KW Three Phase",
    "sections": "12KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "141",
    "material": "DEYE",
    "code": "DT15",
    "name": "DEYE ONGRID 15KW Three Phase",
    "sections": "15KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "142",
    "material": "DEYE",
    "code": "DT18",
    "name": "DEYE ONGRID 18KW Three Phase",
    "sections": "18KW 3 PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "143",
    "material": "DEYE",
    "code": "DT20",
    "name": "DEYE ONGRID 20KW Three Phase",
    "sections": "20KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "144",
    "material": "DEYE",
    "code": "DT25",
    "name": "DEYE ONGRID 25KW Three Phase",
    "sections": "25KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "145",
    "material": "DEYE",
    "code": "DT33",
    "name": "DEYE ONGRID 33KW Three Phase",
    "sections": "33KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "146",
    "material": "DEYE",
    "code": "DT40",
    "name": "DEYE ONGRID 40KW Three Phase",
    "sections": "40KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "147",
    "material": "DEYE",
    "code": "DT50",
    "name": "DEYE ONGRID 50KW Three Phase",
    "sections": "50KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "148",
    "material": "DEYE",
    "code": "DT60",
    "name": "DEYE ONGRID 60KW Three Phase",
    "sections": "60KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "149",
    "material": "DEYE",
    "code": "DT80",
    "name": "DEYE ONGRID 80KW Three Phase",
    "sections": "80KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "150",
    "material": "DEYE",
    "code": "DT90",
    "name": "DEYE ONGRID 90KW Three Phase",
    "sections": "90KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "151",
    "material": "DEYE",
    "code": "DT100",
    "name": "DEYE ONGRID 100KW Three Phase",
    "sections": "100KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "152",
    "material": "DEYE",
    "code": "DT110",
    "name": "DEYE ONGRID 110Kw Three Phase",
    "sections": "110KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "153",
    "material": "DEYE",
    "code": "DT125",
    "name": "DEYE ONGRID 125KW Three Phase",
    "sections": "125KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "154",
    "material": "DEYE",
    "code": "DT136",
    "name": "DEYE ONGRID 136KW Three Phase",
    "sections": "136KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "155",
    "material": "DEYE H",
    "code": "DHS3-24",
    "name": "DEYE HYBRID 3KW - 24V - LV - Single Phase",
    "sections": "3KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "156",
    "material": "DEYE H",
    "code": "DHS3-48",
    "name": "DEYE HYBRID 3KW - 48V - LV - Single Phase",
    "sections": "3KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "157",
    "material": "DEYE H",
    "code": "DHS3.6",
    "name": "DEYE HYBRID 3.6KW - 48V - LV - Single Phase",
    "sections": "3.6KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "158",
    "material": "DEYE H",
    "code": "DHS5",
    "name": "DEYE HYBRID 5KW - 48V - LV - Single Phase",
    "sections": "5KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "159",
    "material": "DEYE H",
    "code": "DHS6",
    "name": "DEYE HYBRID 6KW - 48V - LV - Single Phase",
    "sections": "6KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "160",
    "material": "DEYE H",
    "code": "DHS8",
    "name": "DEYE HYBRID 8KW - 48V - LV - Single Phase",
    "sections": "8 KW 1 PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "161",
    "material": "DEYE H",
    "code": "DHT8",
    "name": "DEYE HYBRID 8KW - 48V - LV - Three Phase",
    "sections": "8KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "162",
    "material": "DEYE H",
    "code": "DHT10",
    "name": "DEYE HYBRID 10KW - 48V - LV - Three Phase",
    "sections": "10KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "163",
    "material": "DEYE H",
    "code": "DHT12",
    "name": "DEYE HYBRID 12KW - 48V - LV - Three Phase",
    "sections": "12KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "164",
    "material": "DEYE H",
    "code": "DHT15",
    "name": "DEYE HYBRID 15KW - 48V - LV - Three Phase",
    "sections": "15KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "165",
    "material": "DEYE H",
    "code": "DHT20",
    "name": "DEYE HYBRID 20KW - 48V - LV - Three Phase",
    "sections": "20KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "166",
    "material": "DEYE H",
    "code": "DHT30",
    "name": "DEYE HYBRID 30KW - HV - Three Phase",
    "sections": "30KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "167",
    "material": "DEYE H",
    "code": "DHT40",
    "name": "DEYE HYBRID 40KW - HV - HYBRID Inverter",
    "sections": "40KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "168",
    "material": "DEYE H",
    "code": "DHT50",
    "name": "DEYE HYBRID 50KW - HV - HYBRID Inverter",
    "sections": "50KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "169",
    "material": "DEYE H",
    "code": "DHT60",
    "name": "DEYE HYBRID 60KW - HV - HYBRID Inverter",
    "sections": "60KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "170",
    "material": "DEYE H",
    "code": "DHT70",
    "name": "DEYE HYBRID 70KW - HV - HYBRID Inverter",
    "sections": "70KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "171",
    "material": "DEYE H",
    "code": "DHT80",
    "name": "DEYE HYBRID 80KW - HV - HYBRID Inverter",
    "sections": "80KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "172",
    "material": "DEYE H",
    "code": "DHT100",
    "name": "DEYE HYBRID 100KW HV HYBRID Inverter",
    "sections": "100KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "173",
    "material": "DEYE H",
    "code": "DHT125",
    "name": "DEYE HYBRID 125KW HV HYBRID Inverter",
    "sections": "125KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "174",
    "material": "HDG",
    "code": "SL2000",
    "name": "SQ LEG 2000 mm (HDG)",
    "sections": "60*60*2MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "175",
    "material": "HDG",
    "code": "SL2500",
    "name": "SQ LEG 2500 mm (HDG)",
    "sections": "60*60*2MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "176",
    "material": "HDG",
    "code": "SL3000",
    "name": "SQ LEG 3000 mm (HDG)",
    "sections": "60*60*2MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "177",
    "material": "HDG",
    "code": "IL900",
    "name": "ISMC LEG 900",
    "sections": "75*40*40*5MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "178",
    "material": "HDG",
    "code": "IL1500",
    "name": "ISMC LEG 1500",
    "sections": "75*40*40*5MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "179",
    "material": "HDG",
    "code": "SPC50",
    "name": "SQ PURLIN CLEAT 50*70*70",
    "sections": "50*70*70*3MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "180",
    "material": "HDG",
    "code": "SPC130",
    "name": "SQ PURLIN CLEAT 130*70*70",
    "sections": "130*70*70*3MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "181",
    "material": "POLYCAB",
    "code": "PS2",
    "name": "POLYCAB ONGRID  2KW Single Phase",
    "sections": "2KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "182",
    "material": "POLYCAB",
    "code": "PS3",
    "name": "POLYCAB ONGRID 3KW Single Phase",
    "sections": "3KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "183",
    "material": "POLYCAB",
    "code": "PS3.6",
    "name": "POLYCAB ONGRID 3.6KW Single Phase",
    "sections": "3.6 1 PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "184",
    "material": "POLYCAB",
    "code": "PS4",
    "name": "POLYCAB ONGRID 4KW Single Phase",
    "sections": "4KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "185",
    "material": "POLYCAB",
    "code": "PS4.6",
    "name": "POLYCAB ONGRID 4.6KW Single Phase",
    "sections": "4.6KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "186",
    "material": "POLYCAB",
    "code": "PS5",
    "name": "POLYCAB ONGRID 5KW Single Phase",
    "sections": "5KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "187",
    "material": "POLYCAB",
    "code": "PT5",
    "name": "POLYCAB ONGRID 5KW Three Phase",
    "sections": "5KW 3 PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "188",
    "material": "POLYCAB",
    "code": "PS6",
    "name": "POLYCAB ONGRID 6KW Single Phase",
    "sections": "6KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "189",
    "material": "POLYCAB",
    "code": "PT6",
    "name": "POLYCAB ONGRID 6KW Three Phase",
    "sections": "6KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "190",
    "material": "POLYCAB",
    "code": "PT8",
    "name": "POLYCAB ONGRID 8KW Three Phase",
    "sections": "8KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "191",
    "material": "POLYCAB",
    "code": "PT10",
    "name": "POLYCAB ONGRID 10KW Three Phase",
    "sections": "10KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "192",
    "material": "POLYCAB",
    "code": "PT12",
    "name": "POLYCAB ONGRID 12kw Three Phase",
    "sections": "12KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "193",
    "material": "POLYCAB",
    "code": "PT15",
    "name": "POLYCAB ONGRID 15KW Three Phase",
    "sections": "15KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "194",
    "material": "POLYCAB",
    "code": "PT20",
    "name": "POLYCAB ONGRID 20KW Three Phase",
    "sections": "20KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "195",
    "material": "POLYCAB",
    "code": "PT25",
    "name": "POLYCAB ONGRID 25KW Three Phase",
    "sections": "25KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "196",
    "material": "POLYCAB",
    "code": "PT30",
    "name": "POLYCAB ONGRID30KW Three Phase",
    "sections": "30KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "197",
    "material": "POLYCAB",
    "code": "PT40",
    "name": "POLYCAB ONGRID 40KW Three Phase",
    "sections": "40KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "198",
    "material": "POLYCAB",
    "code": "PT50",
    "name": "POLYCAB ONGRID 50KW Three Phase",
    "sections": "50KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "199",
    "material": "POLYCAB",
    "code": "PT60",
    "name": "POLYCAB ONGRID 60KW Three Phase",
    "sections": "60KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "200",
    "material": "POLYCAB",
    "code": "PT75",
    "name": "POLYCAB ONGRID 75KW Three Phase",
    "sections": "75KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "201",
    "material": "POLYCAB",
    "code": "PT100",
    "name": "POLYCAB ONGRID 100KW Three Phase",
    "sections": "100KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "202",
    "material": "POLYCAB",
    "code": "PT110",
    "name": "POLYCAB ONGRID 110KW Three Phase",
    "sections": "110KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "203",
    "material": "POLYCAB",
    "code": "PT125",
    "name": "POLYCAB ONGRID 125KW Three Phase",
    "sections": "125KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "204",
    "material": "GROWATT",
    "code": "GS2",
    "name": "GROWATT ONGRID 2KW Single Phase",
    "sections": "2KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "205",
    "material": "GROWATT",
    "code": "GS3",
    "name": "GROWATT ONGRID 3KW Single Phase",
    "sections": "3KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "206",
    "material": "GROWATT",
    "code": "GS3.3",
    "name": "GROWATT ONGRID 3.3KW Single Phase",
    "sections": "3.3KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "207",
    "material": "GROWATT",
    "code": "GS4.2",
    "name": "GROWATT ONGRID 4.2KW Single Phase",
    "sections": "4.2KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "208",
    "material": "GROWATT",
    "code": "GS5",
    "name": "GROWATT ONGRID 5KW Single Phase",
    "sections": "5KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "209",
    "material": "GROWATT",
    "code": "GS6",
    "name": "GROWATT ONGRID 6KW Single Phase",
    "sections": "6KW 1PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "210",
    "material": "GROWATT",
    "code": "GT5",
    "name": "GROWATT ONGRID 5KW Three Phase",
    "sections": "5KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "211",
    "material": "GROWATT",
    "code": "GT6",
    "name": "GROWATT ONGRID 6KW Three Phase",
    "sections": "6KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "212",
    "material": "GROWATT",
    "code": "GT8",
    "name": "GROWATT ONGRID 8KW Three Phase",
    "sections": "8KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "213",
    "material": "GROWATT",
    "code": "GT10",
    "name": "GROWATT ONGRID 10KW Three Phase",
    "sections": "10KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "214",
    "material": "GROWATT",
    "code": "GT12",
    "name": "GROWATT ONGRID 12KW Three Phase",
    "sections": "12KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "215",
    "material": "GROWATT",
    "code": "GT15",
    "name": "GROWATT ONGRID 15KW Three Phase",
    "sections": "15KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "216",
    "material": "GROWATT",
    "code": "GT20",
    "name": "GROWATT ONGRID 20KW Three Phase",
    "sections": "20KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "217",
    "material": "GROWATT",
    "code": "GT25",
    "name": "GROWATT ONGRID 25KW Three Phase",
    "sections": "25KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "218",
    "material": "GROWATT",
    "code": "GT40",
    "name": "GROWATT ONGRID 40KW Three Phase",
    "sections": "40KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "219",
    "material": "GROWATT",
    "code": "GT50",
    "name": "GROWATT ONGRID 50KW Three Phase",
    "sections": "50KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "220",
    "material": "GROWATT",
    "code": "GT60",
    "name": "GROWATT ONGRID 60KW Three Phase",
    "sections": "60KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "221",
    "material": "GROWATT",
    "code": "GT70",
    "name": "GROWATT ONGRID 70KW Three Phase",
    "sections": "70KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "222",
    "material": "GROWATT",
    "code": "GT80",
    "name": "GROWATT ONGRID 80KW Three Phase",
    "sections": "80KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "223",
    "material": "GROWATT",
    "code": "GT100",
    "name": "GROWATT ONGRID 100KW Three Phase",
    "sections": "100KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "224",
    "material": "GROWATT",
    "code": "GT125",
    "name": "GROWATT ONGRID 125KW Three Phase",
    "sections": "125KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "225",
    "material": "GROWATT",
    "code": "GT250",
    "name": "GROWATT ONGRID 250KW Three Phase",
    "sections": "250KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "226",
    "material": "GROWATT",
    "code": "GT350",
    "name": "GROWATT ONGRID 350KW Three Phase",
    "sections": "350KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "227",
    "material": "SOLARYAAN",
    "code": "SS2.5",
    "name": "SOLARYAAN ONGIRD 2.5KW Single Phase",
    "sections": "2.5KW 3PH",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "228",
    "material": "Industrial Grade",
    "code": "LA810",
    "name": "LORD ADHESIVE GLUE",
    "sections": "400ML",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "229",
    "material": "Industrial Grade",
    "code": "DG",
    "name": "DISPENSER GUN",
    "sections": "",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "230",
    "material": "ADANI (DCR)",
    "code": "ABD540",
    "name": "MODULE - ADANI BIFACIAL DCR 540wp",
    "sections": "540",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "231",
    "material": "ADANI (DCR)",
    "code": "ABD545",
    "name": "MODULE - ADANI BIFACIAL DCR 545wp",
    "sections": "545",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "232",
    "material": "ADANI (DCR)",
    "code": "ABD550",
    "name": "MODULE - ADANI BIFACIAL DCR 550wp",
    "sections": "550",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "233",
    "material": "ADANI (DCR)",
    "code": "ABD555",
    "name": "MODULE - ADANI BIFACIAL DCR 555wp",
    "sections": "555",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "234",
    "material": "ADANI (DCR)",
    "code": "ATD605",
    "name": "MODULE - ADANI TOPCON DCR 605wp",
    "sections": "605",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "235",
    "material": "ADANI (DCR)",
    "code": "ATD615",
    "name": "MODULE - ADANI TOPCON DCR 615wp",
    "sections": "615",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "236",
    "material": "ADANI (DCR)",
    "code": "ATD620",
    "name": "MODULE - ADANI TOPCON DCR 620wp",
    "sections": "620",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "237",
    "material": "ADANI (DCR)",
    "code": "ATD630",
    "name": "MODULE - ADANI TOPCON DCR 630wp",
    "sections": "630",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "238",
    "material": "ADANI (DCR)",
    "code": "ATD635",
    "name": "MODULE - ADANI TOPCON DCR 635wp",
    "sections": "635",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "239",
    "material": "ADANI (NDCR)",
    "code": "ATN615",
    "name": "MODULE - ADANI TOPCON NDCR 615wp",
    "sections": "615",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "240",
    "material": "ADANI (NDCR)",
    "code": "ATN625",
    "name": "MODULE - ADANI TOPCON NDCR 625wp",
    "sections": "625",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "241",
    "material": "WAREE (DCR)",
    "code": "WBD540",
    "name": "MODULE - WAREE BIFACIAL DCR 540wp",
    "sections": "540",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "242",
    "material": "WAREE (DCR)",
    "code": "WTD560",
    "name": "MODULE - WAREE TOPCON DCR 560wp",
    "sections": "560",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "243",
    "material": "WAREE (DCR)",
    "code": "WTD580",
    "name": "MODULE - WAREE TOPCON DCR 580wp",
    "sections": "580",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "244",
    "material": "WAREE (DCR)",
    "code": "WTD585",
    "name": "MODULE - WAREE TOPCON DCR 585wp",
    "sections": "585",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "245",
    "material": "WAREE (DCR)",
    "code": "WTD610",
    "name": "MODULE - WAREE TOPCON DCR 610wp",
    "sections": "610",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "246",
    "material": "WAREE (NDCR)",
    "code": "WTN590",
    "name": "MODULE - WAREE TOPCON NDCR 590wp",
    "sections": "590",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "247",
    "material": "LOOM (NDCR)",
    "code": "LBN550",
    "name": "MODULE - LOOM BIFACIAL NDCR 550wp",
    "sections": "550",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "248",
    "material": "RENEW (DCR)",
    "code": "RBD540",
    "name": "RENEW BIFACIAL DCR 540wp",
    "sections": "540",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "249",
    "material": "RENEW (DCR)",
    "code": "RBD545",
    "name": "RENEW BIFACIAL DCR 545wp",
    "sections": "545",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "250",
    "material": "RENEW (DCR)",
    "code": "RBD550",
    "name": "RENEW BIFACIAL DCR 550wp",
    "sections": "550",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "251",
    "material": "SUNBOND (DCR)",
    "code": "SBD545",
    "name": "SUNBOND BIFACIAL DCR 545wp",
    "sections": "545",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "252",
    "material": "SUNBOND (DCR)",
    "code": "SBD550",
    "name": "SUNBOND BIFACIAL DCR 550wp",
    "sections": "550",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "253",
    "material": "SUNBOND (DCR)",
    "code": "STD595",
    "name": "SUNBOND TOPCON DCR 595wp",
    "sections": "595",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "254",
    "material": "VIKRAM (DCR)",
    "code": "VBD550",
    "name": "VIKRAM BIFACIAL DCR 550wp",
    "sections": "550",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "255",
    "material": "VIKRAM (DCR)",
    "code": "VTD600",
    "name": "VIKRAM TOPCON DCR 600wp",
    "sections": "600",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "256",
    "material": "VIKRAM (NDCR)",
    "code": "VTN590",
    "name": "VIKRAM TOPCON NDCR 590wp",
    "sections": "590",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "257",
    "material": "VIKRAM (NDCR)",
    "code": "VTN630",
    "name": "VIKRAM TOPCON NDCR 630wp",
    "sections": "630",
    "uom": "NOS",
    "gst": "5%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "258",
    "material": "FRP",
    "code": "WW310",
    "name": "WALKWAY 310MM",
    "sections": "310MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "259",
    "material": "FRP",
    "code": "WW273",
    "name": "WALKWAY 273MM",
    "sections": "273MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "260",
    "material": "NYLON",
    "code": "CT",
    "name": "CABLE TIE",
    "sections": "300MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "261",
    "material": "ELECTRICAL GRADE",
    "code": "RL",
    "name": "RING LUGS (4-6 mm)",
    "sections": "4-6 mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "262",
    "material": "ELECTRICAL GRADE",
    "code": "PL",
    "name": "PIN LUGS (4-6 mm)",
    "sections": "4-6 mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "263",
    "material": "PVC",
    "code": "CTR",
    "name": "CABLE TRAY",
    "sections": "",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "264",
    "material": "ELECTRICAL GRADE",
    "code": "MC4",
    "name": "MC4 CONNECTOR",
    "sections": "4-6 mm",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "265",
    "material": "6063T6",
    "code": "MR100N",
    "name": "100mm mini rail (new)",
    "sections": "350MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "266",
    "material": "6063T6",
    "code": "MR100O",
    "name": "100mm mini rail (old)",
    "sections": "350MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "267",
    "material": "6063T6",
    "code": "MR40",
    "name": "40mm mini rail",
    "sections": "350MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "268",
    "material": "6063T6",
    "code": "MR60",
    "name": "60mm mini rail",
    "sections": "350MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "269",
    "material": "6063T6",
    "code": "AR100",
    "name": "100mm Adhesive rail",
    "sections": "350MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "270",
    "material": "6063T6",
    "code": "AR120",
    "name": "120mm Adhesive rail",
    "sections": "350MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "271",
    "material": "6063T6",
    "code": "MR100N",
    "name": "100mm mini rail (new)",
    "sections": "400MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "272",
    "material": "6063T6",
    "code": "MR100O",
    "name": "100mm mini rail (old)",
    "sections": "400MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "273",
    "material": "6063T6",
    "code": "MR40",
    "name": "40mm mini rail",
    "sections": "400MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "274",
    "material": "6063T6",
    "code": "MR60",
    "name": "60mm mini rail",
    "sections": "400MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "275",
    "material": "6063T6",
    "code": "AR100",
    "name": "100mm Adhesive rail",
    "sections": "400MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "276",
    "material": "6063T6",
    "code": "AR120",
    "name": "120mm Adhesive rail",
    "sections": "400MM",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "277",
    "material": "POLYCAB",
    "code": "AC(1-5)",
    "name": "ACDB (1-5 KW) With MCB AND SPD",
    "sections": "1-5 KW",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "278",
    "material": "POLYCAB",
    "code": "DC(1-5)",
    "name": "DCDB (1-5 KW) With MCB, FUSE AND SPD",
    "sections": "1-5 KW",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "279",
    "material": "POLYCAB",
    "code": "AC(5-10)",
    "name": "ACDB (5-10 KW) With MCB AND SPD",
    "sections": "5-10 KW",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "280",
    "material": "POLYCAB",
    "code": "DC(5-10)",
    "name": "DCDB (5-10 KW) With MCB, FUSE AND SPD",
    "sections": "5-10 KW",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  },
  {
    "sno": "285",
    "material": "FRP",
    "code": "HR",
    "name": "HAND RAIL",
    "sections": "",
    "uom": "NOS",
    "gst": "18%",
    "price": 0,
    "rate": 0,
    "description": ""
  }
];

export const wordFingerprint = (str) => {
  if (!str) return '';
  const words = str.toLowerCase().replace(/[^a-z0-9]/g, ' ').split(/\s+/).filter(w => w && !['300mm', '350mm', '400mm', 'nos', 'mm'].includes(w));
  return Array.from(new Set(words)).sort().join('_');
};

export const resolveProductCode = (item, productsList = VRM_PRODUCTS) => {
  if (!item) return '';
  const direct = String(item.code || item.sku || '').trim().toUpperCase();
  if (direct && direct !== 'VRM-ITEM' && direct !== 'ITEM' && !direct.startsWith('FG-')) {
    return direct;
  }

  const rawName = String(item.name || item.description || '').toLowerCase().trim();
  if (!rawName) return direct || '';

  // 1. Direct name match in products catalog
  const exact = productsList.find(p => p.name && p.name.toLowerCase().trim() === rawName);
  if (exact && exact.code) return exact.code.toUpperCase();

  // 2. Word fingerprint match
  const fp = wordFingerprint(rawName);
  if (fp) {
    const fpMatch = productsList.find(p => p.name && wordFingerprint(p.name) === fp);
    if (fpMatch && fpMatch.code) return fpMatch.code.toUpperCase();
  }

  // 3. Fallback: check if rawName includes code or code includes in name
  const subMatch = productsList.find(p => {
    const pCode = String(p.code || '').toLowerCase();
    const pName = String(p.name || '').toLowerCase();
    return (pCode && rawName.includes(pCode)) || (pName && rawName.includes(pName)) || (pName && pName.includes(rawName));
  });
  if (subMatch && subMatch.code) return subMatch.code.toUpperCase();

  return direct || '';
};
